In [7]:
import os
from dotenv import load_dotenv
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

load_dotenv()

True

In [10]:
mongodb_connection_string = os.environ.get('MONGODB_CONNECTION_STRING')
mongoClient = MongoClient(mongodb_connection_string)
db = mongoClient.lageranmeldungen
print("Connected to database")

# Set up the collection name
registrations_kinderlager = db['registrations']

# Get all entries in the collection and convert to a list of dictionaries
data = list(registrations_kinderlager.find())

Connected to database

KeyError: "['_id'] not found in axis"

In [20]:
# Create a DataFrame from the list of dictionaries
df_kinderlager = pd.DataFrame(data)
df_kinderlager = df_kinderlager.drop('_id', 1)
#df_kinderlager["birthday"] = df_kinderlager["birthday"].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').date())
print(df_kinderlager.columns)
df_kinderlager

Index(['sexe', 'childLastName', 'childFirstName', 'parentsLastName',
       'parentsFirstName', 'birthday', 'email', 'phone', 'phoneAlternative',
       'address', 'plz', 'city', 'memberOf', 'experience', 'supervisors',
       'insurance', 'tetanus', 'swim', 'swimAllowed', 'vegetarian', 'milk',
       'issues', 'availability', 'alternativeAddress', 'sonst'],
      dtype='object')

C:\Users\ma-hu\AppData\Local\Temp\ipykernel_3152\1350374632.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_kinderlager = df_kinderlager.drop('_id', 1)

,sexe,childLastName,childFirstName,parentsLastName,parentsFirstName,birthday,email,phone,phoneAlternative,address,...,insurance,tetanus,swim,swimAllowed,vegetarian,milk,issues,availability,alternativeAddress,sonst
0,w,Hornung,Franziska,Hornung,Nicole und Klaus,2012-01-18,nicole.hornung@arcor.de,0162-3499644 (Nicole),0160-2644362 (Klaus),Mittelgasse 3,...,Privat versichert ueber Klaus Hornung bei der ...,1,1,1,0,1,keine,1,,Das es wieder so toll wird wie im letzten Jahr 🤗
1,w,Foki,Mia,Foki,Stefanie,2011-02-05,straier@web.de,0178-9310197,0771-1735278,Kirchstr. 27,...,DAK Gesundheit,1,1,1,0,1,,1,,
2,m,Chambi Beyrle,Elias,Beyrle,Andrea,2009-12-01,Beyrleandrea@yahoo.de,+491749801575,,Zaehringerstrasse.4,...,AOK,1,1,1,0,1,,1,,
3,m,Zorn,Ludwig,Zorn,Christine,2010-02-10,christine.zorn@web.de,015175014695,07718967806,Dekan- Metz- Strasse 2,...,AOK,1,1,1,0,1,,1,,
4,m,Zorn,Georg,Zorn,Christine,2013-01-28,christine.zorn@web.de,015175014695,07718967806,Dekan- Metz- Strasse 2,...,AOK,1,1,1,0,1,,1,,
5,w,Zimmermann,Sophia,Zimmermann,Patrik und Daniela,2010-10-06,D.Zimmermann@autohauszimmermann.de,01728864083,01714809636,Obere Gerbe 4,...,DAK,1,1,1,0,1,,1,,
6,w,Gassenschmidt,Martha,Gassenschmidt,Holger und Tanja,2009-10-11,gassenschmidt@gmx.net,0178/3758895,0152/02825665,Schillerstr. 15,...,AOK,1,1,1,0,1,,1,,
7,w,Gassenschmidt,Frida,Gassenschmidt,Holger und Tanja,2013-02-07,gassenschmidt@gmx.net,0178/3758895,0152/02825665,Schillerstr. 15,...,AOK,1,1,1,0,1,,1,,
8,w,Hug,Dana,Hug,Ramona,2010-04-18,ramona.hug@gmx.de,0771/89886374,,Birkenweg 6,...,Barmer,1,1,1,0,1,,1,,
9,w,Federle,Jana,Lohrer,Yvonne,2010-06-07,yviloh@gmx.de,077163990,016091104489,Eschenweg 9,...,AOK Baden-Wuerttemberg,1,1,1,0,1,,1,,
10,w,Federle,Lina,Lohrer,Yvonne,2010-06-07,yviloh@gmx.de,077163990,016091104489,Eschenweg 9,...,AOK Baden-Wuerttemberg,1,1,1,0,1,,1,,
11,w,Baechle,Paulina,Baechle,Melanie,2012-06-26,melanie.baechle@yahoo.de,01625372181,07711751494,Fackenhaldenweg 1,...,Privat,1,1,1,0,1,,1,,
12,w,Wetzel,Lia,Wetzel,Matthias,2012-09-01,mwetzel82@gmail.com,01789311735,015112518863,Gumppstrasse 11,...,AOK,1,1,1,0,1,,1,,
13,w,Vogt,Malou,Vogt,Anja,2011-10-28,Vogt.nussbaumer@web.de,01743245905,0771/64299,Niederwiesen 8,...,DAK,1,1,1,0,1,,1,,
14,m,Heine,Lukas,Rentschler,Angelika,2012-06-29,angelikarentschler@icloud.com,015115598814,,Bregtalstrasse 9,...,Privat,1,1,1,0,1,,1,,
15,w,Gantert,Lucy,Gantert,Thomas und Yvonne,2010-02-10,yvonnegantert@live.de,01741990976,017621700038,Galgebergstrasse 28,...,Techniker Krankenkasse,1,1,1,0,1,,1,,
16,w,Fehrenbach,Hanna,Fehrenbach,Benedikt/ Ilona,2010-05-11,ilonafehrenbach@gmail.com,0771 17515527,015901117035,Sommergasse 24,...,AOK,1,1,1,0,0,,1,,
17,m,Knapp,Benjamin,Knapp,Katrin und Christian,2012-11-19,Katrinknapp@gmx.de,01799223004,01799223005,Kantstr. 3,...,Debeka,1,1,1,0,1,,1,,
18,m,Knapp,Johannes,Knapp,Katrin und Christian,2009-11-11,Katrinknapp@gmx.de,01799223004,01799223005,Kantstr. 3,...,Debeka,1,1,1,0,1,,1,,
19,w,Dury,Lijana,Dury,Josephine und Johannes,2012-06-12,dury2020@web.de,01709340552,016099692340,Biethstr. 4a,...,AOK Donaueschingen,1,1,1,0,1,,1,,
20,w,Faller,Kasia,Bofinger,Beate,2010-02-06,beatebofinger@gmail.com,017662226117,,Untere Gerbe 8,...,AOK,1,1,1,0,1,Fenistil Tropfen darf sie eigenstaendig nehmen,1,,
21,w,Hall,Franziska,Hall,Stephanie,2009-11-30,stephanie@hall.im,07705 256665,015170056665,Bregtalstr.13,...,Privat,1,1,1,0,1,,3,In der Zeit vom 04.-06.08.2023 Silvia und Ott...,
22,w,Frey,Klara Elisabeth,Frey,Anne,2012-02-23,kvika80@web.de,017632867567,077192039777,Mozartstrasse 13,...,DAK,1,1,1,0,1,Einmal Tgl Medikamente; eine Tablette,1,,
23,w,Schenk,Dana,Schenk,Simone und Andreas,2010-06-27,mone.schenk@googlemail.com,07705/338017,0174/3241920,Burgring 8,...,BKK mhplus,1,1,1,0,1,,1,,
24,w,Schenk,Hanna,Schenk,Simone und Andreas,2013-05-28,mone.schenk@googlemail.com,07705/338017,0174/3241920,Burgring 8,...,BKK mhplus,1,1,1,0,1,,1,,
25,m,Ganter,Dominik,Ganter,Tanja,2010-08-09,tanja.ganter@gmx.net,01622384285,01733406444,Holderstr.23,...,AOK Baden-Wuerttemberg,0,1,1,0,1,,1,,
26,m,Ganter,Philipp,Ganter,Tanja,2010-08-09,tanja.ganter@gmx.net,01622384285,01733406444,Holderstr.23,...,AOK Baden-Wuerttemberg,0,1,1,0,1,,1,,
27,w,Bekc,Melek,Bekc,Ali und Christine,2012-07-16,c.wirich@gmx.de,0771 2040640,+491711044094,Im Rosengaertle 2,...,Techniker Krankenkasse,1,1,1,0,1,,1,,
28,m,Bekc,Julian,Bekc,Ali und Christine,2009-08-08,c.wirich@gmx.de,0771 2040640,+491711044094,Im Rosengaertle 2,...,HKK,1,1,1,0,1,,1,,
29,m,Ritter,Luis,Ritter,Tina,2010-10-14,ritter.tina@gmx.de,0771 8969428,0177 5712471,Kantstr. 1,...,Techniker Krankenkasse,0,1,1,0,1,,1,,
30,w,Hannah Isele,Hannah,Isele,Jessica,2012-02-17,isele.jessica0208@web.de,015117117981,,Diessenhoferstrasse 19,...,Signal Iduna,1,1,1,0,1,,1,,
31,w,Marx,Lilli,Marx,Birgit,2012-11-11,bridget.schneider@ gmx.net,017621804918,0771921214,Widmannstr 7,...,Debeka,1,1,1,0,1,,1,,
32,m,Baur,Nico,Baur Manuel,Baur Michaela,2010-09-21,Mbaur85@gmx.de,0771 17512203,,Frankenstrasse 13,...,AOK,1,1,1,0,1,Bienen und Wespengift Allergie,1,,
33,m,Baur,Jan,Baur Michaela,Baur Manuel,2013-01-11,mbaur85@gmx.de,0771 17512203,,Frankenstrasse 13,...,AOK,1,1,1,0,1,,1,,
34,w,Hasenfratz,Lena,Hasenfratz,Nadine und Bernd,2011-07-13,hasi72b@gmx.de,01743287682,01634832774,Faerbergasse 9,...,Aok,1,1,1,0,1,,1,,Ich moechte gerne mit Dana Schenk und Sophia Z...
35,m,Frey,Felix,Frey,Harald,2010-06-23,frey.harald_001@gmx.de,017684842808,,Alemannenstrasse 2,...,Siemens BK,1,1,1,0,1,,1,,
36,w,Mueller,Larissa,Mueller,Sandra,2012-09-20,saenderle@web.de,015751755288,015222553006,Widmannstrasse; 2,...,IKK classic,1,1,1,0,0,,1,,
37,m,Elsholz,Marlon,Elsholz,Birgit und Martin,2011-03-17,birgit.elsholz@gmx.de,0771/8978625,0173/6988552; 0174/8132925,Widmannstrasse 4,...,vivida bkk Schwenningen,1,1,1,0,0,,1,,
38,m,Bossert,Paul,Bossert,Klaus,2009-10-29,Sandrawehinger@gmx.de,077079880200,015774232573,Ignaz-Weisser str. 1,...,AOK,1,1,1,0,1,Neurodermites; Nussalergie;Madelalergie,1,,
39,m,Merk,Moritz,Merk,Heike und Martin,2010-05-02,merkheike@web.de,07718966842,01635671998,Leo-Wohleb-Strasse 14,...,Ikk Classic,1,1,1,0,1,Im Geschaeft (Heike) vormittags = 0771 12828 M...,1,,Bitte mit dem Bruder (Maximilian) oder Kumpel...
40,m,Merk,Maximilian,Merk,Heike und Martin,2013-06-08,merkheike@web.de,07718966842,0162 5671998,Leo-Wohleb-Strasse 14,...,IKK Classic,1,1,1,0,1,Im Geschaeft Heike (vormittags) TEL. 0771 - 12...,1,,Bitte mit dem Bruder (Moritz) oder mit dem Kum...
41,m,Renoth,Aron,Renoth,Daniel & Stefanie,2013-10-11,stefanie.renoth@arcor.de,015906718277,017666333127,Leo Wohleb Strasse 3,...,IKK classic,1,1,1,0,1,,1,,Ich bin erst am 11.10.2013 geboren; allerdings...
42,m,Renoth,Eric,Renoth,Daniel und Stefanie,2010-08-14,stefanie.renoth@arcor.de,015906718277,017666333127,Leo Wohleb Strasse 3,...,IKK classic,1,1,1,0,1,,1,,Es waere cool wenn ich mit meinem kleinen Brud...
43,m,Mahler,Lucas,Mahler,Annabelle und Christian,2011-11-14,annabellemahler@yahoo.de,017663254102,076547999248,Kapellenstrasse 7,...,Vivida BKK,1,1,1,0,1,Annabelle Mahler Kapellenstrasse 7 78199 Braeu...,1,,
44,m,Gantert,Ben,Gantert,Anita,2011-11-02,Gantertgeb@googlemail.com,0173/9467479,0176/22930471,Haldenweg 4,...,Hanse Mercure privat,1,1,1,0,1,,1,,
45,w,Heini,Katharina,Heini,Christoph und Annette,2013-06-28,annette-heini@gmx.de,01705812246,01729355814,Reichenauerstr. 1,...,Privat ( Debeka),1,1,1,0,1,Allergie gegen viele Sonnencremen.,1,,
46,m,Hauptvogel,Henrik,Hauptvogel,Alexandra,2011-08-01,a.hauptvogel@web.de,015227807023,01726251101,Gauchachstrasse 13a,...,Mhplus,1,1,1,0,1,,1,,
47,w,Baumeister,Natalie,Baumeister,Andreas,2010-04-17,baumeisterandreas@web.de,07707 / 9877736,01713486978,Gauchachstrasse 5,...,AOK Baden Wuerttemberg,1,1,1,0,1,,1,,Natalie moechte waehrend des Lagers wieder in ...
48,w,Baumeister,Lena,Baumeister,Andreas,2012-12-13,baumeisterandreas@web.de,07707 / 9877736,01713486978,Gauchachstrasse 5,...,AOK Baden Wuerttemberg,1,1,1,0,1,,1,,
49,w,Sidler,Lucy,Sidler,Daniela,2013-04-18,danielasidler@googlemail.com,077078724010,015254049022,Emil Frei Strasse 6,...,KKH,1,1,1,0,1,,1,,
50,w,Fromm,Ella-Maria,Reimann-Fromm,Ina,2010-10-15,ina-reimann@t-online.de,07718969141,01708064952,Bregenbergstr.20,...,AOK,1,1,1,0,1,,1,,
51,m,Fromm,Moritz,Reimann-Fromm,Ina,2012-10-28,ina-reimann@t-online.de,07718969141,01708064952,Bregenberstr.20,...,AOK,1,1,1,0,1,Moritz hat eine fruehkindliche Form von Migrae...,1,,
52,m,Faller,Gabriel,Faller,Peter und Sandra,2010-10-14,peter.faller@t-online.de,07707/988936,01714319170 oder 015111590118,Hofwiesen 10,...,AOK,1,1,1,0,1,,1,,
53,w,Muja,Amelie,Scherzinger-Muja,Stefanie,2011-03-21,scherzingermuja@gmail.com,07718975865,01736990789,Altes Straessle 3,...,AOK,1,1,1,0,1,allergisches Asthma; hat Spray; kann selbst da...,1,,
54,m,Boesch,Bennet,Boesch,Nicole,2013-01-24,N.Boesch@gmx.de,0771-9294687,0175-7224698,Schillerstrasse 1,...,TKK,1,1,1,0,0,generell keine Milch,1,,
55,m,Sandow,Tim-Luca,Sandow,Marcel,2013-02-09,marcel.sandow83@gmail.com,015207754000,,Muehlenstrasse 11,...,Barmer,1,1,1,0,1,Heuschnupfen,1,,
56,w,Mara,Bengelsdorf,Bengelsdorf,Andrea,2012-09-03,mbengelsdorf@web.de,01631642516,01636403789,Leo-Wohleb-Str. 20,...,Debeka,1,1,1,0,1,,1,,
57,m,Hepting,Emil,Hepting,Katrin,2011-08-18,Katrin-hepting@web.de,015117117952,01789311432,Galgenbergstr.11,...,AOK,1,1,1,0,1,,1,,

In [23]:
m = df_kinderlager.query('sexe == "m"')
md = df_kinderlager.query('sexe == "m" and city == "Doeggingen"')
m1 = df_kinderlager.query('sexe == "m" and birthday > "2012-08-29" and city != "Doeggingen"')
m2 = df_kinderlager.query('sexe == "m" and birthday < "2012-08-30" and birthday > "2011-08-29" and city != "Doeggingen"')
m3 = df_kinderlager.query('sexe == "m" and birthday < "2011-08-30" and birthday > "2010-08-29" and city != "Doeggingen"')
m4 = df_kinderlager.query('sexe == "m" and birthday < "2010-08-30" and city != "Doeggingen"')

,sexe,childLastName,childFirstName,parentsLastName,parentsFirstName,birthday,email,phone,phoneAlternative,address,...,insurance,tetanus,swim,swimAllowed,vegetarian,milk,issues,availability,alternativeAddress,sonst
38,m,Bossert,Paul,Bossert,Klaus,2009-10-29,Sandrawehinger@gmx.de,077079880200,015774232573,Ignaz-Weisser str. 1,...,AOK,1,1,1,0,1,Neurodermites; Nussalergie;Madelalergie,1,,
52,m,Faller,Gabriel,Faller,Peter und Sandra,2010-10-14,peter.faller@t-online.de,07707/988936,01714319170 oder 015111590118,Hofwiesen 10,...,AOK,1,1,1,0,1,,1,,