In [8]:
import os
from dotenv import load_dotenv
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

load_dotenv(dotenv_path='../backend/.env')

True

In [9]:
mongodb_connection_string = os.environ.get('MONGODB_CONNECTION_STRING')
mongoClient = MongoClient(mongodb_connection_string)
db = mongoClient.lageranmeldungen2026
print("Connected to database")

# Set up the collection name
registrations_kinderlager = db['kinderlager']
registrations_xxl = db['xxl']

# Get all entries in the collection and convert to a list of dictionaries
data = list(registrations_kinderlager.find())
data_xxl = list(registrations_xxl.find())

Connected to database

In [15]:
# Create a DataFrame from the list of dictionaries
df_kinderlager = pd.DataFrame(data)
df_kinderlager = df_kinderlager.drop(columns=['_id'])

df_xxl = pd.DataFrame(data_xxl)
df_xxl = df_xxl.drop(columns=['_id'])
#df_kinderlager["birthday"] = df_kinderlager["birthday"].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').date())
#print(df_kinderlager.columns)
#df_kinderlager

In [16]:
df_kinderlager

,sexe,childLastName,childFirstName,parentsLastName,parentsFirstName,birthday,email,phone,phoneAlternative,address,...,doctor,tetanus,swim,swimAllowed,vegetarian,milk,issues,availability,alternativeAddress,sonst
0,w,Vosseler,Luisa,Vosseler / Vosseler-Vogler,Joerg / Ulrike,2015-07-29,joerg.vosseler@t-online.de,+491605733980,+49 174 6972934,Brunnenweg 1a,...,Kinderarzt Dr. Schmidt Donaueschingen,1,1,1,0,1,,1,,Adresse Vater: Joerg Vosseler; Eichbergstrass...
1,w,Heini,Katharina,Heini,Christoph und Annette,2013-06-28,Annette-heini@gmx.de,01705812246,01729355814,Reichenauerstr.1,...,Dr.Schmidt,1,1,1,0,1,,1,,
2,m,Sell,Noah,Sell,Jennifer,2014-02-11,Jennifer_mantel@web.de,017680651942,,Seestrasse.3,...,Dr. Burghart,1,1,1,0,NaN,Heuschnupfen,1,,
3,w,Sell,Lena,Sell,Jennifer,2016-02-22,Jennifer_mantel@web.de,017680561942,,Seestrasse.3,...,Dr. Burghart,1,1,1,0,NaN,,1,,
4,w,Heini,Paulina,Heini,Christoph und Annette,2016-02-07,Annette-heini@gmx.de,01705812246,01729355814,Reichenauerstr.1,...,Dr. Schmidt Donaueschingen,1,1,1,0,NaN,,1,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,m,Hasenfratz,Lukas,Hasenfratz,Nadine und Bernd,2014-02-10,Hasi72b@gmx.de,01743287682,01634832774,Faerbergasse 9,...,Dr. Burghardt und Schmidt,1,1,1,0,NaN,,1,,
63,w,Schuetz,Sina,Schuetz,Carmen und Matthias,2014-09-06,carmen13schuetz@gmx.de,07707 9881082,0174 6894694,Emil-Frei-Strasse 7,...,Dr. med. Andreas Schmidt,1,1,1,0,NaN,,1,,
64,w,Schneider,Nele,Schneider,Nadine &Hendric,2016-08-19,familie@dschneiders.de,+491739726019,+491714816214,Josef Kunz Strasse 2,...,Dr. Burghardt und Schmidt,1,1,1,1,NaN,,1,,
65,m,Wetzel,Daniel,Wetzel,Matthias / Christine,2015-09-26,mwetzel82@gmail.com,01789311735,015112518863,Gumppstrasse 11,...,Dr. med. Andreas Schmidt Dr. med. Claudia Burk...,1,1,1,0,NaN,,3,Christine Wetzel +49 162 1545724 Irmtraud Trai...,Waere gerne zusammen mit Lukas Hasenfratz o. L...
66,w,Mossbrugger,Emely Sophie,Mossbrugger,Elke,2015-02-23,elkemossbrugger@web.de,01791455597,,Sommergasse 12,...,Dr. Schmidt Donaueschingen,1,1,1,0,NaN,,1,,Falls Elke nicht erreichbar sein sollte; bitte...

In [17]:
df_kinderlager["city"] = df_kinderlager["city"].str.strip()

In [19]:
queryNotDoeggingen ='and city != "Doeggingen" and memberOf != "Ministranten Doeggingen"'
m = df_kinderlager.query('sexe == "m"')
md = df_kinderlager.query('sexe == "m" and (city == "Doeggingen" or memberOf == "Ministranten Doeggingen")')
md["group"] = "md"
m1 = df_kinderlager.query('sexe == "m" and birthday > "2015-07-29" ' + queryNotDoeggingen)
m1["group"] = "m1"
m2 = df_kinderlager.query('sexe == "m" and birthday < "2015-07-30" and birthday > "2014-07-29" ' + queryNotDoeggingen)
m2["group"] = "m2"
m3 = df_kinderlager.query('sexe == "m" and birthday < "2014-07-30" and birthday > "2013-07-29" ' + queryNotDoeggingen)
m3["group"] = "m3"
m4 = df_kinderlager.query('sexe == "m" and birthday < "2013-07-30" ' + queryNotDoeggingen)
m4["group"] = "m4"

w = df_kinderlager.query('sexe == "w"')
wd = df_kinderlager.query('sexe == "w" and (city == "Doeggingen" or memberOf == "Ministranten Doeggingen")')
wd["group"] = "wd"
w1 = df_kinderlager.query('sexe == "w" and birthday > "2015-07-29" ' + queryNotDoeggingen)
w1["group"] = "w1"
w2 = df_kinderlager.query('sexe == "w" and birthday < "2015-07-30" and birthday > "2014-07-29" ' + queryNotDoeggingen)
w2["group"] = "w2"
w3 = df_kinderlager.query('sexe == "w" and birthday < "2014-07-30" and birthday > "2013-07-29" ' + queryNotDoeggingen)
w3["group"] = "w3"
w4 = df_kinderlager.query('sexe == "w" and birthday < "2013-07-30" ' + queryNotDoeggingen)
w4["group"] = "w4"

print("Kinder insgesamt:", len(df_kinderlager))
print("-------------------------------")
print("Jungs insgesamt:", len(m))
print("Dögginger Jungs:", len(md))
print("M1 (? und ?):", len(m1))
print("M2 (? und ?):", len(m2))
print("M3 (Eric und Hannes):", len(m3))
print("M4 (Jari und Luis):", len(m4))
print("-------------------------------")
print("Mädels insgesamt:", len(w))
print("Dögginger Mädels:", len(wd))
print("W1 (? und ?):", len(w1))
print("W2 (? und ?):", len(w2))
print("W3 (Jule und Marie):", len(w3))
print("W4 (Maria und Maja):", len(w4))

Kinder insgesamt: 67
-------------------------------
Jungs insgesamt: 27
Dögginger Jungs: 0
M1 (? und ?): 9
M2 (? und ?): 9
M3 (Eric und Hannes): 5
M4 (Jari und Luis): 4
-------------------------------
Mädels insgesamt: 40
Dögginger Mädels: 6
W1 (? und ?): 10
W2 (? und ?): 13
W3 (Jule und Marie): 4
W4 (Maria und Maja): 7

In [ ]:
m3["memberOf"]

m2

In [20]:
df_kinderlager_grouped = pd.concat([md, m1, m2, m3, m4, wd, w1, w2, w3, w4], axis=0)
#df_kinderlager_grouped.to_excel('anmeldungen.xlsx', index=False)

In [21]:
df_kinderlager_grouped

,sexe,childLastName,childFirstName,parentsLastName,parentsFirstName,birthday,email,phone,phoneAlternative,address,...,tetanus,swim,swimAllowed,vegetarian,milk,issues,availability,alternativeAddress,sonst,group
16,m,Lautemann,Erik,Lautemann,Jennifer,2016-05-22,jennifer-lautemann@gmx.de,017632982846,0173 7217315,Alemannenstr. 20,...,1,1,1,0,NaN,,1,,,m1
24,m,Glatz,Josef,Gross / Glatz,Andrea / Markus,2016-01-16,gross-andrea@freenet.de,017623705865,,Doeggingerstr. 44,...,1,1,1,0,NaN,,1,,,m1
25,m,Zirlewagen,Rio,Zirlewagen,Juergen,2016-09-19,juergen.zirlewagen@gmx.de,01624082569,,Bruggenerstr 1,...,1,1,1,0,NaN,,1,,,m1
34,m,Azevedo,Emil,Azevedo,Sandra & Sven,2016-03-16,Sandraazevedo@gmx.de,015789282110,01629631349,Doeggingerstr.13,...,1,1,1,0,NaN,,1,,,m1
40,m,Hauser,Max,Hauser,Elisabeth; Richard,2015-09-03,E.hauser88@web.de,01626165823,0771 89888574,Doegginger Strasse 41,...,1,1,1,0,NaN,,1,,,m1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21,w,Schenk,Hanna,Schenk,Simone und Andreas,2013-05-28,mone.schenk@googlemail.com,07705-338017,0174-3241920,Burgring 8,...,1,1,1,0,NaN,,1,,,w4
22,w,Gassenschmidt,Frida,Gassenschmidt,Holger und Tanja,2013-02-07,gassenschmidt@gmx.net,01783758895,,Schillerstrasse 15,...,1,1,1,0,NaN,,1,,,w4
26,w,Scherer,Emmy,Scherer,Andreas,2013-04-20,a.scherer1975@gmx.de,015117117993,01629842547,Im Rosengaertle 12,...,1,1,1,0,NaN,,1,,,w4
39,w,Mueller,Larissa,Zirlewagen,Sandra,2012-09-20,sandra.zirlewagen@web.de,015751755288,015222553006 (Papa),Widmannstrasse 2,...,1,1,1,0,NaN,,1,,Larissa kann beim Essen keine harten Lebensmit...,w4
42,w,Knappe,Emma,Rahm / Knappe,Marion / Stefan,2012-08-31,marion.rahm@web.de,0174 16 23 280,0171 880 7500,Fuchsstrasse 13,...,1,1,1,0,NaN,,1,,,w4

In [23]:
df_kinderlager_grouped.to_excel('anmeldungen_kinderlager_2026.xlsx', index=False)

In [35]:
count_m = df_xxl["sexe"].isin(["m"]).sum()
count_w = df_xxl["sexe"].isin(["w"]).sum()
print(f"Jungs: {count_m} / Mädels: {count_w}")

# extract year and count
year_counts = df_xxl["birthday"].str[:4].value_counts().sort_index()

print("--------------\n", year_counts)

Jungs: 10 / Mädels: 14
--------------
 birthday
2009    1
2010    8
2011    7
2012    8
Name: count, dtype: int64

In [25]:
df_xxl.to_excel('anmeldungen_xxl_2026.xlsx', index=False)

In [ ]:
auswaerts = df_kinderlager_grouped.query('city != "Doeggingen" and city != "Braeunlingen"')
colsToDrop = ["tetanus", "swim", "swimAllowed", "milk", "phone", "phoneAlternative"]
auswaerts = auswaerts.drop(colsToDrop, 1)
auswaerts