In [1]:
import os
from dotenv import load_dotenv
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

load_dotenv()

True

In [2]:
mongodb_connection_string = os.environ.get('MONGODB_CONNECTION_STRING')
mongoClient = MongoClient(mongodb_connection_string)
db = mongoClient.lageranmeldungen2024
print("Connected to database")

# Set up the collection name
registrations_kinderlager = db['kinderlager']
registrations_xxl = db['xxl']

# Get all entries in the collection and convert to a list of dictionaries
data = list(registrations_kinderlager.find())
data_xxl = list(registrations_xxl.find())

Connected to database

In [3]:
# Create a DataFrame from the list of dictionaries
df_kinderlager = pd.DataFrame(data)
df_kinderlager = df_kinderlager.drop('_id', 1)

df_xxl = pd.DataFrame(data_xxl)
df_xxl = df_xxl.drop('_id', 1)
#df_kinderlager["birthday"] = df_kinderlager["birthday"].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').date())
#print(df_kinderlager.columns)
#df_kinderlager

C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\3091324495.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_kinderlager = df_kinderlager.drop('_id', 1)
C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\3091324495.py:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_xxl = df_xxl.drop('_id', 1)

In [4]:
df_kinderlager["city"] = df_kinderlager["city"].str.strip()

In [5]:
df_kinderlager

,sexe,childLastName,childFirstName,parentsLastName,parentsFirstName,birthday,email,phone,phoneAlternative,address,...,doctor,tetanus,swim,swimAllowed,vegetarian,milk,issues,availability,alternativeAddress,sonst
0,w,Fobel,Ariana,Fobel,Deborah,2013-08-28,d-c.fobel@gmx.de,015787047224,+4915204371762 Oliver Moritz,Galgenbergstrasse 15,...,Dr. Merzkirch in VS- Schwenningen,1,1,1,0,0,,1,,Ariana moechte zusammen mit Hanna Waimer (aus ...
1,w,Dury,Lijana,Dury,Josephine,2012-06-12,dury2020@web.de,01709340552,,Biethstr.4a,...,Dr.Selemann,1,1,1,0,1,,1,,
2,m,Schaefer,Noah,Schaefer,Melanie und Christian,2013-04-04,meli-schaefer81@web.de,017664663400,,Schillerstrasse 8,...,Dr. med. Andreas Schnidt,1,1,1,0,1,,1,,
3,w,Foki,Mia,Foki,Stefanie,2011-02-05,Straier@web.de,0178-9310197,0771-1735278,Kirchstr. 27,...,Dr. Schmidt,1,1,1,0,1,,1,,
4,m,Heine,Lukas,Rentschler / Heine,Angelika / Martin,2012-06-29,angelikarentschler@icloud.com,+4977052209846,015115598814,Bregtalstrasse 9,...,Dr. Schmidt; Donaueschingen,1,1,1,0,1,,1,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,m,Maier,Jens,Maier-Hagen,Judith,2011-03-05,judith.hagen@web.de,07733503652,017653489180,Hermann-Buergermeister-Str. 25,...,Dr. Strobel / Burchhardt Engen,1,1,1,0,1,keine Allergien; keine Medikamente darf bei Be...,1,,Jens moechte gerne das Zeltlager besuchen; da ...
78,m,Kinzner,Lennart,Kinzner,Ilka und Matthias,2010-11-19,kinz@gmx.de,077339827020,01721020920,Zum Alpenblick 10,...,Dr. Krix,1,1,1,0,1,Heuschnupfen (Lennart nimmt nach Bedarf und ei...,1,,Da Lennart seinen Freund (Jens Maier; ebenfall...
79,m,Laule,Filip,Corcodel / Laule,Elena / Markus,2012-05-07,elenacorcodel@yahoo.com,01638647290,07707 988 729,Freiburger Strasse 13,...,Kinderarztpraxis Burkhard Schmidt Donaueschingen,1,1,1,0,1,,1,,
80,w,Enderlin,Helen,Ziereisen,Susanne,2010-07-05,susanneziereisen@gmx.de,07628803131,01747880990 /01737660950,Hutgasse 14,...,Dr. Petra Herm Efringen-Kirchen 07628/3310000,1,1,1,1,0,,1,,
81,m,Marques Rodrigues,Dinis,Rodrigues Marques,Ana Sofia,2011-09-09,Herrdinis@gmail.com,+4915223819480,+4915223819853,Gauchachstr.11,...,D. Dold,1,0,1,0,1,,1,,

In [6]:
queryNotDoeggingen ='and city != "Doeggingen" and memberOf != "Ministranten Doeggingen"'
m = df_kinderlager.query('sexe == "m"')
md = df_kinderlager.query('sexe == "m" and (city == "Doeggingen" or memberOf == "Ministranten Doeggingen")')
md["group"] = "md"
m1 = df_kinderlager.query('sexe == "m" and birthday > "2013-07-29" ' + queryNotDoeggingen)
m1["group"] = "m1"
m2 = df_kinderlager.query('sexe == "m" and birthday < "2013-07-30" and birthday > "2012-07-29" ' + queryNotDoeggingen)
m2["group"] = "m2"
m3 = df_kinderlager.query('sexe == "m" and birthday < "2012-07-30" and birthday > "2011-07-29" ' + queryNotDoeggingen)
m3["group"] = "m3"
m4 = df_kinderlager.query('sexe == "m" and birthday < "2011-07-30" ' + queryNotDoeggingen)
m4["group"] = "m4"

w = df_kinderlager.query('sexe == "w"')
wd = df_kinderlager.query('sexe == "w" and (city == "Doeggingen" or memberOf == "Ministranten Doeggingen")')
wd["group"] = "wd"
w1 = df_kinderlager.query('sexe == "w" and birthday > "2013-07-29" ' + queryNotDoeggingen)
w1["group"] = "w1"
w2 = df_kinderlager.query('sexe == "w" and birthday < "2013-07-30" and birthday > "2012-07-29" ' + queryNotDoeggingen)
w2["group"] = "w2"
w3 = df_kinderlager.query('sexe == "w" and birthday < "2012-07-30" and birthday > "2011-07-29" ' + queryNotDoeggingen)
w3["group"] = "w3"
w4 = df_kinderlager.query('sexe == "w" and birthday < "2011-07-30" ' + queryNotDoeggingen)
w4["group"] = "w4"

print("Kinder insgesamt:", len(df_kinderlager))
print("-------------------------------")
print("Jungs insgesamt:", len(m))
print("Dögginger Jungs:", len(md))
print("M1 (Eric und Hannes):", len(m1))
print("M2 (Jari und Luis):", len(m2))
print("M3 (Loris und Leon):", len(m3))
print("M4 (Ringo):", len(m4))
print("-------------------------------")
print("Mädels insgesamt:", len(w))
print("Dögginger Mädels:", len(wd))
print("W1 (Jule und Marie):", len(w1))
print("W2 (Maria und Maja):", len(w2))
print("W3 (Lina und Vanessa):", len(w3))
print("W4 (Evelyn und Sophia):", len(w4))

Kinder insgesamt: 82
-------------------------------
Jungs insgesamt: 36
Dögginger Jungs: 6
M1 (Eric und Hannes): 11
M2 (Jari und Luis): 7
M3 (Loris und Leon): 5
M4 (Ringo): 7
-------------------------------
Mädels insgesamt: 46
Dögginger Mädels: 7
W1 (Jule und Marie): 8
W2 (Maria und Maja): 12
W3 (Lina und Vanessa): 9
W4 (Evelyn und Sophia): 10

C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\773565713.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  md["group"] = "md"
C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\773565713.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m1["group"] = "m1"
C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\773565713.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m2["group"] = "m2"
C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\773565713.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m3["group"] = "m3"
C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\773565713.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m4["group"] = "m4"
C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\773565713.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wd["group"] = "wd"
C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\773565713.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  w1["group"] = "w1"
C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\773565713.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  w2["group"] = "w2"
C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\773565713.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  w3["group"] = "w3"
C:\Users\ma-hu\AppData\Local\Temp\ipykernel_10740\773565713.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  w4["group"] = "w4"

In [ ]:
m3["memberOf"]

m2

In [7]:
df_kinderlager_grouped = pd.concat([md, m1, m2, m3, m4, wd, w1, w2, w3, w4], axis=0)
#df_kinderlager_grouped.to_excel('anmeldungen.xlsx', index=False)

In [8]:
df_kinderlager_grouped

,sexe,childLastName,childFirstName,parentsLastName,parentsFirstName,birthday,email,phone,phoneAlternative,address,...,tetanus,swim,swimAllowed,vegetarian,milk,issues,availability,alternativeAddress,sonst,group
7,m,van Geete,Beckett,van Geete,Kathleen u. Sascha,2011-06-23,kvangeete@gmail.com,01774641476,01774641484,Im Gaessle 4,...,1,1,1,1,1,Beckett hat ADHS und nimmt jeden morgen eine M...,1,,,md
9,m,van Geete,Orpheus,van Geete,Sascha u. Kathleen,2013-01-16,kvangeete@gmail.com,01774641484,01774641476,Im Gaessle 4,...,1,1,1,1,1,Orpheus hat ADHS und nimmt eine Medikament jed...,1,,,md
63,m,Seiferle,Jannik,Seiferle,Sybille,2011-09-12,s.seiferle@web.de,O7707 988196,017699083800,Hofwiesen 8,...,1,1,1,0,1,,1,,,md
71,m,Flihs,Levi,Flihs,Birgit,2012-08-12,birgitleiche@web.de,07707989393,01799118438,Am Muehleweg 2,...,1,1,1,0,1,Heuschnupfen; Migraene,1,,,md
79,m,Laule,Filip,Corcodel / Laule,Elena / Markus,2012-05-07,elenacorcodel@yahoo.com,01638647290,07707 988 729,Freiburger Strasse 13,...,1,1,1,0,1,,1,,,md
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,w,Fromm,Ella-Maria,Reimann-Fromm,Ina,2010-10-15,ina-reimann@t-online.de,01708064952,07718969141,Bregenbergstr.20,...,1,1,1,0,1,,1,,,w4
54,w,Dold,Nora,Dold,Boris,2011-04-03,dold@bioas-hochreiter.de,0174-3058474,0173-3128906,Ottilienbergstrasse 6,...,1,1,1,0,1,,1,,Ich waere gerne mit Lena Hasenfratz und Sophia...,w4
66,w,Wilkens,Leonie,Wilkens,Kerstin und Patrick,2011-01-30,kerstinw1984@gmx.de,0771-92918502,01578-1053636,Biethstr. 3,...,1,1,1,0,1,Allergie gegen Ibuprofen und alle Medikamente ...,1,,Ich moechte bitte zusammen mit den Maedchen au...,w4
72,w,Waesch,Sophia-Marie,Waesch,Barbara,2010-12-09,tobias2lang@gmail.com,01797431183,,Im Rosengaertle 10,...,1,1,1,0,1,,1,,,w4
80,w,Enderlin,Helen,Ziereisen,Susanne,2010-07-05,susanneziereisen@gmx.de,07628803131,01747880990 /01737660950,Hutgasse 14,...,1,1,1,1,0,,1,,,w4

In [ ]:
df_kinderlager_grouped.to_excel('anmeldungen_kinderlager.xlsx', index=False)

In [ ]:
df_xxl.to_excel('anmeldungen_xxl.xlsx', index=False)

In [ ]:
auswaerts = df_kinderlager_grouped.query('city != "Doeggingen" and city != "Braeunlingen"')
colsToDrop = ["tetanus", "swim", "swimAllowed", "milk", "phone", "phoneAlternative"]
auswaerts = auswaerts.drop(colsToDrop, 1)
auswaerts